load("output/egk_brt_model")

plotdata.elev <- plot(kang.brt, i.var = 1, return.grid=TRUE, type="response")
plotdata.light <- plot(kang.brt, i.var = 3, return.grid=TRUE, type="response")
plotdata.precdm <- plot(kang.brt, i.var = 5, return.grid=TRUE, type="response")

tiff('figs/light.tif', pointsize = 12, compression = "lzw", res=300, width = 900, height = 900)
par(mgp=c(2.0,0.5,0),mar=c(3.5,3.5,1,1), cex.axis=0.8)
plot(plotdata.light, type="l", ylab="KANGAROO OCCURRENCE", xlab="LIGHT", yaxt="n", ylim=c(0,0.25), xaxt="n", bty="n", lwd=1)
axis(1, lwd = 0.2)
axis(2, lwd = 0.2)
box(lwd=0.3)
dev.off()

tiff('figs/elev.tif', pointsize = 12, compression = "lzw", res=300, width = 900, height = 900)
par(mgp=c(2.0,0.5,0),mar=c(3.5,3.5,1,1), cex.axis=0.8)
plot(plotdata.elev, type="l", ylab="KANGAROO OCCURRENCE", xlab="ELEV", yaxt="n", ylim=c(0,0.25), xaxt="n", bty="n", lwd=1)
axis(1, lwd = 0.2)
axis(2, lwd = 0.2)
box(lwd=0.3)
dev.off()

tiff('figs/precdm.tif', pointsize = 12, compression = "lzw", res=300, width = 900, height = 900)
par(mgp=c(2.0,0.5,0),mar=c(3.5,3.5,1,1), cex.axis=0.8)
plot(plotdata.precdm, type="l", ylab="KANGAROO OCCURRENCE", xlab="PRECDM", yaxt="n", ylim=c(0,0.25), xaxt="n", bty="n", lwd=1)
axis(1, lwd = 0.2)
axis(2, lwd = 0.2)
box(lwd=0.3)
dev.off()